export const machineData = [
  "Drill Machine-xxxx1",
  "Drill Machine-xxxxxxxxxxxxxxxxxxx",
  "HAMUEL VMC",
  "WALDRICH COBURG SURFACE GRINDING",
  "WMW SLIDEWAY GRINDING",
  "WMW SURFACE GRINDING",
  "VIKRAM LATHE",
  "MYSORE KIRLOSKAR LATHE",
  "HURON MILLING M/C",
  "BOEHRINGER TURNING CNC",
  "MIKRON-VC 1000 TNC 407",
  "MAS VR4 RADIAL",
  "HMT RADIAL DRILLING",
  " FLOOR BORING FLORIEP",
  "CSEPEL RADIAL DRILLING",
  "WALDRICH COBURG VMC",
  "TOS VMC",
  " PFEIFER HORIZONTAL BORING",
  "CNC BED TYPE MILLING M/C (BUTLER)",
  "INGERSOLL BOHLE VMC",
  "PINNACLE",
  "CNC DEEP HOLE DRILLING MACHINE (LOCH MAKE)",
  "CNC DEEP HOLE DRILLING MACHINE (HEGENGGHEIDT MAKE)",
  " BANDSAW MACHINE",
  "GEMINI CNC LATHE",
  "PUNJAB MAKE LATHE MACHINE",
  "TAPPING MACHINE",
  "SURFACE GRINDING MACHINE (CAMUT)",
  "Bench",
  "Johnford VMC 1 ",
  "Johnford VMC 2",
  "Press machine 100 ton",
  " EDM MACHINE",
  " WELDING M/C",
  "PULSE OXIMETER",
  "TEMPERATURE MACHINE",
  "Compressor No 1 ALUP",
  " Compressor No 2 Atlas",
  "Hydraulic Jack No 1",
  "Hydraulic Jack No 2",
  " Pedestal Fan No 1 ( PF 1)",
  "Pedestal Fan No 2 (PF 2)",
  " Pedestal Fan No 3 (PF 3)",
  "Pedestal Fan No 4 (PF 4)",
  "Pedestal Fan No 5 (PF 5)",
  " Blower Fan No 1 (BF 1) _ Near WMW Slideway Grinding",
  "Blower Fan No 2 (BF 2) _ Near WMW Surface Grinding",
  " Blower Fan No 3 (BF 3) _ Near Waldrich Grinding",
  " Blower Fan No 4 (BF 4) _ Near Camut Grinding",
  "Blower Fan No 5 (BF 5) _ Near Vikram Lathe ",
  " Blower Fan No 6 (BF 6) _ Near Boehringer Turning",
  "Blower Fan No 7 (BF 7) _ Near Johnford No 1",
  " Blower Fan No 8 (BF 8) _ Near TOS VMC",
  " Crane No 1 SWL 10Ton",
  "Crane No 2 SWL 10 Ton",
  "Crane No 3 SWL 10 Ton",
  "Crane No 4 SWL 10 Ton",
  "Crane No 5 SWL 5 Ton",
  "HP LASERJET PROFESSIONAL M1135 - 1ST FLOOR",
  " HP LASERJET PROFESSIONAL M1135 - GROUND FLOOR",
  "S ROCCO BORING",
];

export const toolList = [
  "PLAIN PLUG GAUGE 6H7",
  "PLAIN PLUG GAUGE 8H7",
  "PLAIN PLUG GAUGE 10H7",
  "PLAIN PLUG GAUGE 12H7",
  "PLAIN PLUG GAUGE 20H8",
  "PLAIN PLUG GAUGE 30H8",
  "THREAD PLUG GAUGE M6",
  "THREAD PLUG GAUGE M8",
  "THREAD PLUG GAUGE M10",
  "THREAD PLUG GAUGE M12",
  "THREAD PLUG GAUGE M16",
  "THREAD PLUG GAUGE M24",
  "THREAD PLUG GAUGE M30",
  "PLUNGER DIAL 0.001",
  "PLUNGER DIAL 0.002",
  "PLUNGER DIAL 0.005",
  "PLUNGER DIAL 0.01",
  "LEVER DIAL 0.002",
  "LEVER DIAL 0.01",
  "VERNIER CALIPER 0-300",
  "VERNIER CALIPER 0-600",
];

export const processList = [
  "MACHINING",
  "TOP SIDE ROUGH MACHINING",
  "SECOND SIDE ROUGH MACHINING",
  "FIRST SIDE ROUGH MACHINING",
  "FINISH MACHINING",
  "TAP M-20",
  "TOP SIDE FINISH MACHINING",
  "SETTING",
  "SIDE ROUGH MACHINING",
  "SIDE FINISH MACHINING",
  "बॉटम मशिनिंग करणे.",
  "H7 BORE",
  "बोअरिंग करणे.",
  "SLOT MACHINING",
  "REAMING",
  "STEP MACHINING",
  "TOP SIDE GRINDING",
  "BOTTOM SIDE GRINDING",
  "SIDE GRINDING",
  "TAP M-3",
  "TAP M-4",
  "TAP M-5",
  "TAP M-6",
  "TAP M-8",
  "TAP M-10",
  "TAP M-12",
  "TAP M-14",
  "TAP M-16",
  "TAP M-18",
  "TAP M-24",
  "TAP M-30",
  "TAPPING M24X2",
  "GRINDING",
  "8H7",
  "12H7",
  "SLOT ROUGH MACHINING",
  "SLOT FINISH MACHINING",
  "डीबरिंग करणे.",
  "सेंटरिंग करणे.",
  "ड्रिलिंग करणे.",
  "IN PROCESS INSPECTION",
  "JOB UNLOADING",
  "TOTAL LENGTH MACHINING",
  "SPOT FACE",
  "FACE CUT",
  "BORE OD ROUGH MC",
  "रफ बोअरिंग करणे.",
  "TOP SIDE ROUGH MC",
  "बॉटम रफ मशिनिंग करणे.",
  "बॉटम फिनिश मशिनिंग करणे.",
  "BORE OD FIN MC",
  "TOP LMA MC",
  "SIDE MC ROUGH",
  "SIDE MC FIN",
  "TOP IN SIDE MC",
  "REF CUT",
  "TOP ROUGH MC",
  "TOP FIN MACHINING",
  "SEND TO GRINDING",
  "TOP SIDE PAD MC",
  "TOP MC",
  "PAD MC",
  "DRILLING 1",
  "TAPPING",
  "Pointing",
  "Slide Mounting Angular Grinding",
  "Tailstock Mounting Angular Grinding",
  "STRESS RELIEVING",
  "Marking",
  "Finishing Operations (Dbr/Cln/Hand Tapping)",
  "Marking and Hand Drilling",
  "जॉबचा प्रोसेस चार्ट बनविण्यापूर्वी त्याच्या शक्य त्या साईजेस चेक करून घेणे",
  "जॉब लोड करण्यापूर्वी ड्रॉईंग आणि प्रोसेस चार्ट प्रोडक्शन इन्चार्जने सुपरवायजरला समजावून सांगणे",
  "जॉब लोड करण्यापूर्वी ड्रॉईंग आणि प्रोसेस चार्ट सुपरवायजरने मशीन ऑपरेटरला समजावून सांगणे",
  "MACHINE CLEAN & UNWANTED MATERIAL RETURN",
  "ALL OPERATIONS DONE",
  "ALL SIZES CHECKED",
  "बॉटम फेस पॅरलल ब्लॉकवर रेस्ट करून ट्रू करून क्लॅम्प करणे.",
  "टॉप फेस पॅरलल ब्लॉकवर रेस्ट करून ट्रू करून क्लॅम्प करणे.",
  "बॉटम फेस स्क्रू जॅकवर रेस्ट करून ट्रू करून क्लॅम्प करणे.",
  "टॉप फेस स्क्रू जॅकवर रेस्ट करून ट्रू करून क्लॅम्प करणे.",
  "टॉप फेस रफ मिलिंग करणे.",
  "टॉप फेस फिनिश मिलिंग करणे.",
  "बॉटम फेस फिनिश मिलिंग करणे.",
  "बॉटम फेस रफ मिलिंग करणे.",
  "साईड फेस रफ मिलिंग करणे.",
  "साईड फेस फिनिश मिलिंग करणे.",
  "हाईट फिनिश करणे.",
  "विड्थ फिनिश मशिनिंग करणे.",
  "लेंग्थ फिनिश मशिनिंग करणे. ",
  "फेस व स्टेप मिलिंग करणे.",
  "फेस व स्लॉट मिलिंग करणे.",
  "स्लॉट मिलिंग करणे.",
  "पॉकेट मिलिंग करणे",
  "1st Setup operations",
  "2nd setup Operations",
  "3rd Setup Operations",
  "IN-PROCESS INSPECTION",
  "थिकनेस रफ मशिनिंग करणे.",
  "थिकनेस फिनिश मशिनिंग करणे.",
  "विड्थ रफ मशिनिंग करणे.",
  "लेंग्थ रफ मशिनिंग करणे.",
  "OPERATIONAL INSPECTION",
  "DIMENSIONAL INSPECTION",
  "BOTTOM ROUGH MACHINING",
  "TOP ROUGH MACHINING",
  "Thk Rough Machining",
  "Thk Finish Machining",
  "Machine cleaning",
  "Setting Material Action ",
];

export const userName = ["Pratiksha", "Pradnya"];
