export const machineData = [
  "Drill Machine-xxxx1",
  "Drill Machine-xxxxxxxxxxxxxxxxxxx",
  "HAMUEL VMC",
  "WALDRICH COBURG SURFACE GRINDING",
  "WMW SLIDEWAY GRINDING",
  "WMW SURFACE GRINDING",
  "VIKRAM LATHE",
  "MYSORE KIRLOSKAR LATHE",
  "HURON MILLING M/C",
  "BOEHRINGER TURNING CNC",
  "MIKRON-VC 1000 TNC 407",
  "MAS VR4 RADIAL",
  "HMT RADIAL DRILLING",
  " FLOOR BORING FLORIEP",
  "CSEPEL RADIAL DRILLING",
  "WALDRICH COBURG VMC",
  "TOS VMC",
  " PFEIFER HORIZONTAL BORING",
  "CNC BED TYPE MILLING M/C (BUTLER)",
  "INGERSOLL BOHLE VMC",
  "PINNACLE",
  "CNC DEEP HOLE DRILLING MACHINE (LOCH MAKE)",
  "CNC DEEP HOLE DRILLING MACHINE (HEGENGGHEIDT MAKE)",
  " BANDSAW MACHINE",
  "GEMINI CNC LATHE",
  "PUNJAB MAKE LATHE MACHINE",
  "TAPPING MACHINE",
  "SURFACE GRINDING MACHINE (CAMUT)",
  "Bench",
  "Johnford VMC 1 ",
  "Johnford VMC 2",
  "Press machine 100 ton",
  " EDM MACHINE",
  " WELDING M/C",
  "PULSE OXIMETER",
  "TEMPERATURE MACHINE",
  "Compressor No 1 ALUP",
  " Compressor No 2 Atlas",
  "Hydraulic Jack No 1",
  "Hydraulic Jack No 2",
  " Pedestal Fan No 1 ( PF 1)",
  "Pedestal Fan No 2 (PF 2)",
  " Pedestal Fan No 3 (PF 3)",
  "Pedestal Fan No 4 (PF 4)",
  "Pedestal Fan No 5 (PF 5)",
  " Blower Fan No 1 (BF 1) _ Near WMW Slideway Grinding",
  "Blower Fan No 2 (BF 2) _ Near WMW Surface Grinding",
  " Blower Fan No 3 (BF 3) _ Near Waldrich Grinding",
  " Blower Fan No 4 (BF 4) _ Near Camut Grinding",
  "Blower Fan No 5 (BF 5) _ Near Vikram Lathe ",
  " Blower Fan No 6 (BF 6) _ Near Boehringer Turning",
  "Blower Fan No 7 (BF 7) _ Near Johnford No 1",
  " Blower Fan No 8 (BF 8) _ Near TOS VMC",
  " Crane No 1 SWL 10Ton",
  "Crane No 2 SWL 10 Ton",
  "Crane No 3 SWL 10 Ton",
  "Crane No 4 SWL 10 Ton",
  "Crane No 5 SWL 5 Ton",
  "HP LASERJET PROFESSIONAL M1135 - 1ST FLOOR",
  " HP LASERJET PROFESSIONAL M1135 - GROUND FLOOR",
  "S ROCCO BORING",
];

export const toolList = [
  "BALL NOSE CUTTER DIA 25 x 300",
  "Carbide Endmill 10.0mm",
  "Carbide Endmill 12.0mm",
  "Carbide Endmill 14.0mm",
  "Carbide Endmill 15.5mm",
  "Carbide Endmill 16.0mm",
  "Carbide Endmill 17.5 mm",
  "Carbide Endmill 18.0MM",
  "Carbide Endmill 18.7 MM",
  "Carbide Endmill 19.0mm",
  "Carbide Endmill 20.0mm",
  "Carbide Endmill 20.5MM",
  "Carbide Endmill 22.5MM",
  "Carbide Endmill 29.5 x 50 x 130 mm",
  "Carbide Endmill 29.7 x 55 x 105mm",
  "Carbide Endmill 3.0mm",
  "Carbide Endmill 30 x 55 x 130mm",
  "Carbide Endmill 32 x 45 x 105mm",
  "Carbide Endmill 4.0mm",
  "Carbide Endmill 4.0mm Ball Nose",
  "Carbide Endmill 5.0mm",
  "Collet ER-40 12-11",
  "Collet ER-40 13-12",
  "Collet ER-40 14-13",
  "Collet ER-40 15-14",
  "Collet ER-40 16-15",
  "Collet ER-40 17-16",
  "Collet ER-40 18-17",
  "Collet ER-40 19-18",
  "Collet ER-40 20-19",
  "Collet ER-40 21-20",
  "Collet ER-4022-21",
  "Collet ER-40 23-24",
  "Collet ER-40 24-23",
  "Collet ER-40 25-24",
  "Collet ER-40 26-25",
  "Collet ER-40 3-2",
  "Collet ER-40 4-3",
  "Collet ER-40 6-5",
  "Collet ER-40 7-6",
  "Collet ER-40 8-7",
  "Collet ER-40 9-8",
  "Collet ER-20 11 x 32",
  "Collet ER-20 2-1x32",
  "Collet ER-25 1.0mm",
  "Collet ER-25 13x34",
  "Collet ER-25 2-1x34",
  "Collet ER-25 3x34",
  "COLLET ER 25 x 8-7",
  "Collet ER-32 20-19",
  "Collet ER-40 10-9",
  "Collet ER-40 11-10",
  "Collet ER-40 12-11",
  "Collet ER-40 13-12",
  "Collet ER-40 14-13",
  "Collet ER-40 15-14",
  "Collet ER-40 16-15",
  "Collet ER-40 17-16",
  "Collet ER-40 18-17",
  "Collet ER-40 19-18",
  "Collet ER-40 20-19",
  "Collet ER-40 21-20",
  "Collet ER-40 22-21",
  "Burr Tools Rotary Cutter - Round",
  "Burr Tools Rotary Cutter-T3",
  "Cutter-SLITING 150 x 5MM THK",
  "CUTTER-DIA 25 BALL INSERT CUTTER BODY",
  "Dovetail cutter Dia 30 x 15mm length x 60deg.",
  "HEXA FRAME",
  "HOLSOW CUTTER 20.0 MM",
  "HOLSOW CUTTER 25.0 MM",
  "HOLSOW CUTTER 40.0 MM",
  "Side & Face Cuttar 80x12mm",
  "Side & Face Cuttar 80x32mm With Adpr.",
  "Side & Face Cuttar 8.5x5mm",
  "Side & Face Cuttar Insert Type 100x16mm",
  "Side & Face Cuttar Insert Type 100x30mm",
  "Side & Face Cuttar Insert Type 125x16mm",
  "Side & Face Cuttar Insert Type 250x30mm",
  "Side & Face Cuttar Q 100x5x25",
  "Side & Face Cuttar Q70x6x27",
  "T MAX CUTTER 160.0 MM-R220.69-160-18-10AN",
  "T MAX CUTTER Dia 125.0 Face Mill Cutter",
  "Champer Cutter Insert Type 117.0mm x 45*",
  "Champer Cutter Insert Type 16.0mm x 45*",
  "Champer Cutter Insert Type 20.0mm x 45*",
  "Champer Cutter Insert Type 28.0mm x 150mm x 45*",
  "Champer Cutter Insert Type 30.0mm x 160.0mm x 45*",
  "Champer Cutter Insert Type 45.0mm x 45*",
  "Champer Cutter Insert Type 50.0 x 250 mm x 45*",
  "Champer Cutter Insert Type 50.0mm x 45*",
  "Champer Cutter Insert Type 60.0mm x 60*",
  "Champer Cutter Insert Type Q20-40mm x 45*",
  "Champer Cutter Insert Type Q5-25mm x 45*",
  "Champer Cutter Parallel Shank 10x20mm x 90*",
  "Champer Cutter Parallel Shank 10x45*",
  "Champer Cutter Parallel Shank 13x9.5*(Slot Drill)",
  "Champer Cutter Parallel Shank 20.0mm x 15*",
  "Champer Cutter Parallel Shank 24.0mm",
  "Champer Cutter Parallel Shank 25x45*",
  "Champer Cutter Parallel Shank 26.0mm",
  "Champer Cutter Parallel Shank 3x 90*",
  "Champer Cutter Parallel Shank 48.0mm",
  "Champer Cutter Parallel Shank 50.0mm",
  "Carbide Endmill 17.5mm",
  "Carbide Endmill 18.0MM",
  "Carbide Endmill 18.7MM",
  "Carbide Endmill 19.0mm",
  "Carbide Endmill 20.0mm",
  "Carbide Endmill 20.5MM",
  "Carbide Endmill 22.5MM",
  "Carbide Endmill 29.5 x 50 x 130 mm",
  "Carbide Endmill 29.7 x 55 x 105mm",
  "Carbide Endmill 3.0mm",
  "Carbide Endmill 30 x 55 x 130mm",
  "Carbide Endmill 32 x 45 x 105mm",
  "Carbide Endmill 4.0mm",
  "Carbide Endmill 4.0mm Ball Nose",
  "Carbide Endmill 5.0mm",
  "Carbide Endmill 5.0mm x 6x13x50",
  "Carbide Endmill 6.0 x 100 MM",
  "Carbide Endmill 6.0MM",
  "Carbide Endmill 6.0mm Ball Nose",
  "Carbide Endmill 6.3mm",
  "Carbide Endmill 8.0 mm",
  "Burr Tools Rotary Cutter - Round",
  "Burr Tools Rotary Cutter-T3",
  "Cutter-SLITING 150 x 5MM THK",
  "CUTTER-DIA 25 BALL INSERT CUTTER BODY",
  "Dovetail cutter Dia 30 x 15mm length x 60deg.",
  "HEXA FRAME",
  "HOLSOW CUTTER 20.0 MM",
  "HOLSOW CUTTER 25.0 MM",
  "HOLSOW CUTTER 40.0 MM",
  "Side & Face Cuttar 80x12mm",
  "Side & Face Cuttar 80x32mm With Adpr.",
  "Side & Face Cuttar 8.5x5mm",
  "Side & Face Cuttar Insert Type 100x16mm",
  "Side & Face Cuttar Insert Type 100x30mm",
  "Side & Face Cuttar Insert Type 125x16mm",
  "Side & Face Cuttar Insert Type 250x30mm",
  "Side & Face Cuttar Q 100x5x25",
  "Side & Face Cuttar Q70x6x27",
  "T MAX CUTTER 160.0 MM-R220.69-160-18-10AN",
  "T MAX CUTTER Dia 125.0 Face Mill Cutter",
  "Champer Cutter Insert Type 60.0mm x 60*",
  "Champer Cutter Insert Type Q20-40mm x 45*",
  "Champer Cutter Insert Type Q5-25mm x 45*",
  "Champer Cutter Parallel Shank 10x20mm x 90*",
  "Champer Cutter Parallel Shank 10x45*",
  "Champer Cutter Parallel Shank 13x9.5*(Slot Drill)",
  "Champer Cutter Parallel Shank 20.0mm x 15*",
  "Champer Cutter Parallel Shank 24.0mm",
  "Champer Cutter Parallel Shank 25x45*",
  "Champer Cutter Parallel Shank 26.0mm",
  "Champer Cutter Parallel Shank 3x 90*",
  "Champer Cutter Parallel Shank 48.0mm",
  "Champer Cutter Parallel Shank 50.0mm",
  "Champer Cutter Parallel Sthank 51.0mm x 90*",
  "Champer Cutter Parallel Shank 55.0mm",
  "Champer Cutter Parallel Shank Carbide 16.0mm x 15*",
  "Champer Cutter Parallel Shank Carbide - 20.0mm x 18",
  "Champer Cutter Taper Shank 1.1/2x 90*",
  "Champer Cutter Taper Shank 1/2x 90*",
  "Champer Cutter Taper Shank 3/4x 90*",
  "Collet ER-20 11 x 32",
  "Collet ER-20 2-1x32",
  "Collet ER-25 1.0mm",
  "Collet ER-25 13x34",
  "Collet ER-25 2-1x34",
  "Collet ER-25 3x34",
  "COLLET ER 25 x 8-7",
  "Collet ER-32 20-19",
  "Collet ER-40 10-9",
  "Collet ER-40 11-10",
  "Collet ER-40 12-11",
  "Collet ER-40 13-12",
  "Collet ER-40 14-13",
  "Collet ER-40 15-14",
  "Collet ER-40 16-15",
  "Collet ER-40 17-16",
  "Collet ER-40 18-17",
  "Collet ER-40 19-18",
  "Collet ER-40 20-19",
  "Collet ER-40 21-20",
  "Collet ER-40 22-21",
];

export const processList = [
  "MACHINING",
  "TOP SIDE ROUGH MACHINING",
  "SECOND SIDE ROUGH MACHINING",
  "FIRST SIDE ROUGH MACHINING",
  "FINISH MACHINING",
  "TAP M-20",
  "TOP SIDE FINISH MACHINING",
  "SETTING",
  "SIDE ROUGH MACHINING",
  "SIDE FINISH MACHINING",
  "बॉटम मशिनिंग करणे.",
  "H7 BORE",
  "बोअरिंग करणे.",
  "SLOT MACHINING",
  "REAMING",
  "STEP MACHINING",
  "TOP SIDE GRINDING",
  "BOTTOM SIDE GRINDING",
  "SIDE GRINDING",
  "TAP M-3",
  "TAP M-4",
  "TAP M-5",
  "TAP M-6",
  "TAP M-8",
  "TAP M-10",
  "TAP M-12",
  "TAP M-14",
  "TAP M-16",
  "TAP M-18",
  "TAP M-24",
  "TAP M-30",
  "TAPPING M24X2",
  "GRINDING",
  "8H7",
  "12H7",
  "SLOT ROUGH MACHINING",
  "SLOT FINISH MACHINING",
  "डीबरिंग करणे.",
  "सेंटरिंग करणे.",
  "ड्रिलिंग करणे.",
  "IN PROCESS INSPECTION",
  "JOB UNLOADING",
  "TOTAL LENGTH MACHINING",
  "SPOT FACE",
  "FACE CUT",
  "BORE OD ROUGH MC",
  "रफ बोअरिंग करणे.",
  "TOP SIDE ROUGH MC",
  "बॉटम रफ मशिनिंग करणे.",
  "बॉटम फिनिश मशिनिंग करणे.",
  "BORE OD FIN MC",
  "TOP LMA MC",
  "SIDE MC ROUGH",
  "SIDE MC FIN",
  "TOP IN SIDE MC",
  "REF CUT",
  "TOP ROUGH MC",
  "TOP FIN MACHINING",
  "SEND TO GRINDING",
  "TOP SIDE PAD MC",
  "TOP MC",
  "PAD MC",
  "DRILLING 1",
  "TAPPING",
  "Pointing",
  "Slide Mounting Angular Grinding",
  "Tailstock Mounting Angular Grinding",
  "STRESS RELIEVING",
  "Marking",
  "Finishing Operations (Dbr/Cln/Hand Tapping)",
  "Marking and Hand Drilling",
  "जॉबचा प्रोसेस चार्ट बनविण्यापूर्वी त्याच्या शक्य त्या साईजेस चेक करून घेणे",
  "जॉब लोड करण्यापूर्वी ड्रॉईंग आणि प्रोसेस चार्ट प्रोडक्शन इन्चार्जने सुपरवायजरला समजावून सांगणे",
  "जॉब लोड करण्यापूर्वी ड्रॉईंग आणि प्रोसेस चार्ट सुपरवायजरने मशीन ऑपरेटरला समजावून सांगणे",
  "MACHINE CLEAN & UNWANTED MATERIAL RETURN",
  "ALL OPERATIONS DONE",
  "ALL SIZES CHECKED",
  "बॉटम फेस पॅरलल ब्लॉकवर रेस्ट करून ट्रू करून क्लॅम्प करणे.",
  "टॉप फेस पॅरलल ब्लॉकवर रेस्ट करून ट्रू करून क्लॅम्प करणे.",
  "बॉटम फेस स्क्रू जॅकवर रेस्ट करून ट्रू करून क्लॅम्प करणे.",
  "टॉप फेस स्क्रू जॅकवर रेस्ट करून ट्रू करून क्लॅम्प करणे.",
  "टॉप फेस रफ मिलिंग करणे.",
  "टॉप फेस फिनिश मिलिंग करणे.",
  "बॉटम फेस फिनिश मिलिंग करणे.",
  "बॉटम फेस रफ मिलिंग करणे.",
  "साईड फेस रफ मिलिंग करणे.",
  "साईड फेस फिनिश मिलिंग करणे.",
  "हाईट फिनिश करणे.",
  "विड्थ फिनिश मशिनिंग करणे.",
  "लेंग्थ फिनिश मशिनिंग करणे. ",
  "फेस व स्टेप मिलिंग करणे.",
  "फेस व स्लॉट मिलिंग करणे.",
  "स्लॉट मिलिंग करणे.",
  "पॉकेट मिलिंग करणे",
  "1st Setup operations",
  "2nd setup Operations",
  "3rd Setup Operations",
  "IN-PROCESS INSPECTION",
  "थिकनेस रफ मशिनिंग करणे.",
  "थिकनेस फिनिश मशिनिंग करणे.",
  "विड्थ रफ मशिनिंग करणे.",
  "लेंग्थ रफ मशिनिंग करणे.",
  "OPERATIONAL INSPECTION",
  "DIMENSIONAL INSPECTION",
  "BOTTOM ROUGH MACHINING",
  "TOP ROUGH MACHINING",
  "Thk Rough Machining",
  "Thk Finish Machining",
  "Machine cleaning",
  "Setting Material Action ",
];

export const userName = ["Pratiksha", "Pradnya"];

export const idleCode = [
  { no: 1, name: "No Power (Electricity)" },
  { no: 2, name: "Drawing Issue" },
  { no: 3, name: "Weekly Off" },
  { no: 4, name: "Material Issue" },
  { no: 5, name: "No Crane" },
  { no: 6, name: "No Air" },
  { no: 7, name: "Stores - Collection of Tools/Drags/Instruments/Gauges etc" },
  { no: 8, name: "Minor Machine Breakdown" },
  { no: 9, name: "Waiting for dicision" },
  { no: 10, name: "Discountinue current load" },
  { no: 11, name: "Availability of Co worker load" },
  { no: 12, name: "Operator Absent/ Late mark" },
  { no: 13, name: "No Load/ No Plan" },
  { no: 14, name: "Rework during Operations" },
  { no: 15, name: "Planned Maintainance" },
  { no: 16, name: "Unskilled operator on machine" },
  { no: 17, name: "Use of Worm out tooling/ Tooling problem" },
  { no: 18, name: "Stores - Collection of Tools/Drags/Instruments/Gauges etc" },
  { no: 19, name: "Searching and collecting componenet to be loaded" },
  { no: 20, name: "Operator shifted for other work during operations" },
  { no: 21, name: "Operator not allocated" },
  { no: 22, name: "Process Deviation" },
  { no: 23, name: "Mentance Team Availability" },
  { no: 24, name: "Inspection on Machine" },
];
